from tkinter import *
def setnumber(num):
    equation.set(equation.get()+num)
def cal():
    equation.set(eval(equation.get()))
def sign(s):
    x=equation.get()[-1]
    if x=="+" or x=="-" or x=="*" or x=="/":
        equation.set(equation.get()[:-1]+s)
    else:
        equation.set(equation.get()+s)         
root=Tk()
equation=StringVar()
root.title("calculator")
lbl=Label(root,textvariable=equation,font=("times new roman",20,"bold"),fg="red",width=20,padx=2,pady=2)
lbl.grid(columnspan=4)
btn1=Button(root,text='1',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("1"))
btn1.grid(row=1,column=0)
btn2=Button(root,text='2',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("2"))
btn2.grid(row=1,column=1)
btn3=Button(root,text='3',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("3"))
btn3.grid(row=1,column=2)
btn4=Button(root,text='4',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("4"))
btn4.grid(row=2,column=0)
btn5=Button(root,text='5',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("5"))
btn5.grid(row=2,column=1)
btn6=Button(root,text='6',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("6"))
btn6.grid(row=2,column=2)
btn7=Button(root,text='7',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("7"))
btn7.grid(row=3,column=0)
btn8=Button(root,text='8',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("8"))
btn8.grid(row=3,column=1)
btn9=Button(root,text='9',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("9"))
btn9.grid(row=3,column=2)
btn0=Button(root,text='0',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :setnumber("0"))
btn0.grid(row=4,column=1)
btnplus=Button(root,text='+',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :sign("+"))
btnplus.grid(row=1,column=3)
btnsub=Button(root,text='-',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :sign("-"))
btnsub.grid(row=2,column=3)
btnmul=Button(root,text='*',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :sign("*"))
btnmul.grid(row=3,column=3)
btndiv=Button(root,text='/',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :sign("/"))
btndiv.grid(row=4,column=3)
btnclear=Button(root,text='c',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=lambda :equation.set(""))
btnclear.grid(row=4,column=0)
btnequal=Button(root,text='=',font=("b nazanin",20,"bold"),fg="#EB0CAA" ,bg="#C2B2AE",width=5,height=2,command=cal)
btnequal.grid(row=4,column=2)
root.mainloop()

