from tkinter import *
from tkinter.filedialog import asksaveasfile
screen = Tk()
screen.geometry('500x500')
screen.title('Register Form')
screen.configure(bg='#363834', borderwidth=5,highlightthickness=7, highlightcolor='#e674f4')
formheading = Label(text='فرم ارزیابی', font=('b nazanin',25, "bold"), bg='#363834',fg='#f8ea04', width='500', height='3')
formheading.pack()
firstname_text = Label(text=':نام',font=('b nazanin',14,"bold"),bg='#363834', fg='#04bcf8')
firstname_text.place(x=1800, y=200)
firstname = StringVar()
firstname_entry = Entry(textvariable=firstname, width=60, border=3,highlightthickness=3, highlightcolor='green', highlightbackground='red')
firstname_entry.place(x=1400, y=200)
lastname_text = Label(text=':نام خانوادگی',font=('b nazanin',14,"bold"),bg='#363834', fg='#04bcf8')
lastname_text.place(x=1800, y=250)
lastname = StringVar()
lastname_entry = Entry(textvariable=lastname, width=60, border=3,highlightthickness=3, highlightcolor='green', highlightbackground='red')
lastname_entry.place(x=1400, y=250)
mainloop()   