import turtle
turtle.title("hello")
turtle.pensize(3)
turtle.ht()
list1=input("enter number").split()
turtle.fillcolor("darkred")
turtle.begin_fill()
for i in list1:
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(int(i))
    turtle.right(90)
    turtle.write(i,font=("b nazanin",15,"bold"))
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(int(i))
    turtle.left(90)
    turtle.forward(10)
turtle.end_fill()
turtle.done()
